# Generated by Django 4.1 on 2023-04-30 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='cdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
